language: bash

services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install make autoconf dash
  - sudo apt-get install curl
  - git clone https://github.com/matejak/argbash.git
  - cd argbash/resources
  - make install
  - cd -
  - rm -rf argbash

env:
  global:
    - CODECOV_TOKEN=:"775d989b-44a4-40df-8cc6-b699f432f88a"


os: linux
dist: bionic
script:
    - git checkout  master
    - bash ./build.sh
    - git commit -am 'travis dist build [skip ci]' || true
    - git push origin master || true
    - sudo docker run --security-opt seccomp=unconfined --mount type=bind,source="$(pwd)",target=/source  /source/kcov  /source/tests/test-git-get.sh
    - bash ./tests/test-git-get.sh
depth: false

after_success:
  - bash <(curl -s https://codecov.io/bash)