services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install make autoconf dash
  - printf '%s\n' '#!/bin/bash' 'docker run -it --rm -v "$(pwd):/work" matejak/argbash "$@"' > argbash-docker
  - printf '%s\n' '#!/bin/bash' 'docker run -it -e PROGRAM=argbash-init --rm -v "$(pwd):/work" matejak/argbash "$@"' > argbash-init-docker
  - chmod a+x argbash-docker argbash-init-docker
  - sudo install argbash-docker argbash-init-docker /usr/bin/
  - docker pull kcov/kcov
language: bash
os:
  - linux
dist: bionic
script:
    - git checkout  master
    - bash ./build.sh
    - git commit -am 'travis dist build [skip ci]' || true
    - git push || true
    - kcov --coveralls-id=$TRAVIS_JOB_ID ./tests ./tests/test-git-get.sh
    - bash ./tests/test-git-get.sh
depth: false