#!/usr/bin/env bash

######################################
# git ext_name
#
#
# Installation :
# Add this to the same directory that your git executable is in, and make sure it has executable
# permissions : i.e.: chmod o+x  git-get
#
 # git-same as git clone but without the cloning
#
# Usage:
#
# @author Andrew Druffner andrew@nomstock.com
######################################


#####################
#
# Determine platform
# http://stackoverflow.com/a/18434831
#####################

# NOTE: on macOS, this requires GNU findutils,
# installed using e.g. brew install findutils:
# https://brew.sh/
# https://apple.stackexchange.com/a/69332
case "${OSTYPE}" in
    darwin*)
        grep='ggrep'
        xargs='gxargs'
        ;;
    linux-*)
        grep='grep'
        xargs='xargs'
        ;;
    *)
        echo 'ERROR'
        echo "unsupported operating system: ${OSTYPE}"
        exit 1
        ;;
esac

#####################
#
# GetOpts
# http://stackoverflow.com/a/16496491
#####################
#usage() { echo "Usage: git splits [-f] [-t] -b <branch_name> <dir1> <dir2>" 1>&2; #exit 1; }

#########################
# The command line help #
#########################
usage() {
    echo "Usage: git get [option...] <repository> [<directory>]"
    echo
    echo "   -b          Branch  - branch to copy, defaults to master"
    echo "   -V          Verbose - Shows debugging output"
    echo "   -d          Dry Run - Downloads repo to a temp directory"
    echo "   -v          Version - shows version"
    echo "   -h          Help    - show usage"
    echo
    1>&2;exit 1
}



# intialization
branch=master
dir=
repo_path=
e_messages=
v_messages=
version=1.0.0
while getopts "bVvdh" o;do
    case "${o}" in
        b)

            branch="${OPTARG}"
            v_messages+="-b:branch set to ${branch}\n";
            ;;
        V)
            VERBOSE="TRUE"
            v_messages+="-V:verbose enabled \n";
            ;;
        d)
            DRY_RUN="TRUE"
            v_messages+="-d:dry run enabled \n";
            ;;
        v)
            echo "git-get version $version";
            exit;
            ;;
        h,*)
            usage
            exit;
            ;;
    esac
done
shift $((OPTIND-1))


validate(){

if [ -z "${1}" ]; then
 e_messages+="you forgot to give me a repo path \n";
 end;
else
repo_path="${1}"
fi

if [ "$2" ]; then
  dir="${2}"
fi

}

show_errors () {
 echo -e "$*"
 exit 1;
}

show_verbose () {
    if [ ! -z "${VERBOSE}" ]
    then
        echo -e "$*"
      #  echo "git clone --depth=1 --branch=${branch} ${repo_path} ${dir}" && echo "rm -rf ./${dir}/.git"

    fi
}



#: ${1?"Usage: $0 ARGUMENT"}

#: ${!VERBOSE?"Usage: $0 ARGUMENT"}

end(){
    show_errors "${e_messages}"
    exit;
}


setRepoPath(){
if [ -z "${1}" ]; then
 e_messages+="you forgot to give me a repo path \n";
 end;
else
repo_path="${1}"
fi
}




setDirectory(){
if [ "${dir}" ]; then
return
fi

    re="([^/]+)\.git"
    re_no_extension="([^/]+)$"
if [[ $repo_path =~ $re ]]; then
    dir=${BASH_REMATCH[1]}

elif [[ $repo_path =~ $re_no_extension ]]; then
    dir=${BASH_REMATCH[1]}
else
     e_messages+="invalid path $repo_path \n";
     end;
fi

}




get(){

local temp="${TMPDIR:-/tmp}"
local dirNameTarget=$dir
local dirPathTarget=./$dir;
local dirDryRunTarget=$temp/$dir



local cmd_options='--depth=1 --branch='"${branch}"' '"${repo_path}"' '"${dirPathTarget}"


    if [ ! -z "${DRY_RUN}" ]
    then

echo "dry run..."
dirPathTarget="${dirDryRunTarget}";
rm -rf "${dirDryRunTarget}";

local cmd_options='--depth=1 --branch='"${branch}"' '"${repo_path}"' '"${dirPathTarget}"


     echo "git clone ${cmd_options}"
     echo "git submodule update --init --recursive"
     echo 'rm -rf ./'"${dir}"'/.git'



    fi

if git clone ${cmd_options} ; then

    cd "${dirPathTarget}";
    git submodule update --init --recursive;
    rm -rf "${dirPathTarget}"/.git;


fi


}





######## MAIN ###########
validate  $@
setRepoPath "${1}"
setDirectory  $@
show_verbose "${v_messages}"
get
show_errors "${e_messages}"